### ISSUE TITLE
Network sagemaker-local declared as external, but could not be found.

### ISSUE THREAD

**Issue by emsi** [alexschultz/deepracer-for-dummies#5]
Bringing the containers up spits:

`
ERROR: Network sagemaker-local declared as external, but could not be found. Please create the network manually using `docker network create sagemaker-local` and try again.
`

Since the README says nothing about I guess it's a simple overlook.

**Comment by alexschultz** [comment]
Can you walk me through what you did to set everything up?

**Comment by emsi** [comment]
```
./init.sh
cd docker
docker-compore up
```
Even some random web guide mentions the necessity of `docker network create sagemaker-local`:
https://medium.com/@autonomousracecarclub/how-to-run-deepracer-locally-to-save-your-wallet-13ccc878687

**Comment by Lacan82** [comment]
I believe I am running into an issue with Sagemaker myself. Not sure if it is related but keep getting a message waiting for Sagemaker redis server ip....

**Comment by alexschultz** [comment]
Hey sorry I have been away the past few days. You should not need to manually create the network, if that's what the guide says than it's incorrect. Docker Compose by design sets up the network for all the containers to run in and then as part of that it also does some "magic" under the hood so that the containers can reference each other by container name instead of IP address. Networking is a fundamental part of docker compose. There is something else that is going on with your setup. Try checking the logs of each container to see if anything stands out. To do this you will need to query the containers to get the container IDs using 
"docker ps"
then "docker logs {containerId}" to see the logs for a specific container.
The "redis server ip..." issue has been mentioned in lots of places in the slack community. The person that I saw who had it was because nvidia-docker2 wasn't installed. Not sure if this is your specific issue, the logs should help you to diagnose it further though. If you're still stuck, please post the individual container logs here so I can help troubleshoot.

**Comment by YogeshSharma0201** [comment]
just run `docker network create sagemaker-local`, it worked for me.
